
apiVersion: v1
kind: Secret
metadata:
  name: openbank-secrets
  namespace: openbank
type: Opaque
stringData:
  JWT_SECRET: "change-me-in-prod"
  JWT_EXPIRE: "30d"
  FRONTEND_URL: "http://openbank.local"
